### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by Gemorroj** [cdnjs/cdnjs#4027]
repository https://cdnjs.com/libraries/summernote
file http://cdnjs.cloudflare.com/ajax/libs/summernote/0.5.10/summernote-bs3.css is required some fonts. see: 
```css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('../fonts/glyphicons-halflings-regular.eot');
  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```
but are missing in cdnjs.
